### ISSUE TITLE
Problem in installation

### ISSUE THREAD

**Issue by vikas-chand** [grburgess/pynchrotron#1] opened 2020-10-26 07:47 UTC
Hi, 

The following error when installing occurs
"ERROR: Could not find a version that satisfies the requirement pytables (from astromodels->pynchrotron==1.0.0+1.g9ff0de2) (from versions: none)
ERROR: No matching distribution found for pytables (from astromodels->pynchrotron==1.0.0+1.g9ff0de2)"

I have pytables installed. 

Please help with this.
Thanks.

**Comment by grburgess** [comment] 2020-10-26 09:56
Hi,

This sounds like a issue with your python setup. I'm not sure if I can help without more information.

**Comment by vikas-chand** [comment] 2020-10-26 10:05
Hi,

Thanks for your reply.

I have installed fermitools successfully which is the latest python 3.7 edition. Then, I also installed threeML succesfully and it's working fine. Since astromodels was also installed in this process, it seems that pynchrotron is demanding for a version of pytables which is different than astromodels. 


The detailed output while trying with directly downloading from the git and also pip install are as follows


(base) grbphysics@x86_64-apple-darwin13 pynchrotron-master % pip install pynchrotron Requirement already satisfied: pynchrotron in /Users/grbphysics/anaconda3/envs/threeML/lib/python3.7/site-packages/pynchrotron-0+unknown-py3.7.egg (0+unknown)
Requirement already satisfied: numba in /Users/grbphysics/anaconda3/envs/threeML/lib/python3.7/site-packages (from pynchrotron) (0.51.2)
Requirement already satisfied: numpy in /Users/grbphysics/anaconda3/envs/threeML/lib/python3.7/site-packages (from pynchrotron) (1.19.2)
Requirement already satisfied: astromodels in /Users/grbphysics/anaconda3/envs/threeML/lib/python3.7/site-packages (from pynchrotron) (2.0.0)
Requirement already satisfied: llvmlite<0.35,>=0.34.0.dev0 in /Users/grbphysics/anaconda3/envs/threeML/lib/python3.7/site-packages (from numba->pynchrotron) (0.34.0)
Requirement already satisfied: setuptools in /Users/grbphysics/anaconda3/envs/threeML/lib/python3.7/site-packages (from numba->pynchrotron) (49.6.0.post20201009)
Requirement already satisfied: pandas in /Users/grbphysics/anaconda3/envs/threeML/lib/python3.7/site-packages (from astromodels->pynchrotron) (1.1.3)
Requirement already satisfied: PyYAML>=5.1 in /Users/grbphysics/anaconda3/envs/threeML/lib/python3.7/site-packages (from astromodels->pynchrotron) (5.3.1)
Requirement already satisfied: interpolation in /Users/grbphysics/anaconda3/envs/threeML/lib/python3.7/site-packages (from astromodels->pynchrotron) (2.1.6)
ERROR: Could not find a version that satisfies the requirement pytables (from astromodels->pynchrotron) (from versions: none)
ERROR: No matching distribution found for pytables (from astromodels->pynchrotron)



(base) grbphysics@x86_64-apple-darwin13 pynchrotron-master % conda activate threeML
(threeML) grbphysics@x86_64-apple-darwin13 pynchrotron-master % pip install pynchrotron
Requirement already satisfied: pynchrotron in /Users/grbphysics/anaconda3/envs/threeML/lib/python3.7/site-packages/pynchrotron-0+unknown-py3.7.egg (0+unknown)
Requirement already satisfied: numba in /Users/grbphysics/anaconda3/envs/threeML/lib/python3.7/site-packages (from pynchrotron) (0.51.2)
Requirement already satisfied: numpy in /Users/grbphysics/anaconda3/envs/threeML/lib/python3.7/site-packages (from pynchrotron) (1.19.2)
Requirement already satisfied: astromodels in /Users/grbphysics/anaconda3/envs/threeML/lib/python3.7/site-packages (from pynchrotron) (2.0.0)
Requirement already satisfied: setuptools in /Users/grbphysics/anaconda3/envs/threeML/lib/python3.7/site-packages (from numba->pynchrotron) (49.6.0.post20201009)
Requirement already satisfied: llvmlite<0.35,>=0.34.0.dev0 in /Users/grbphysics/anaconda3/envs/threeML/lib/python3.7/site-packages (from numba->pynchrotron) (0.34.0)
Requirement already satisfied: h5py in /Users/grbphysics/anaconda3/envs/threeML/lib/python3.7/site-packages (from astromodels->pynchrotron) (2.10.0)
ERROR: Could not find a version that satisfies the requirement pytables (from astromodels->pynchrotron) (from versions: none)
ERROR: No matching distribution found for pytables (from astromodels->pynchrotron)
(threeML) grbphysics@x86_64-apple-darwin13 pynchrotron-master % 

(threeML) grbphysics@x86_64-apple-darwin13 pynchrotron-master % conda deactivate 
(base) grbphysics@x86_64-apple-darwin13 pynchrotron-master % conda deactivate
grbphysics@x86_64-apple-darwin13 pynchrotron-master % pip install pynchrotron
Requirement already satisfied: pynchrotron in /Users/grbphysics/anaconda3/envs/threeML/lib/python3.7/site-packages/pynchrotron-0+unknown-py3.7.egg (0+unknown)
Requirement already satisfied: numba in /Users/grbphysics/anaconda3/envs/threeML/lib/python3.7/site-packages (from pynchrotron) (0.51.2)
Requirement already satisfied: numpy in /Users/grbphysics/anaconda3/envs/threeML/lib/python3.7/site-packages (from pynchrotron) (1.19.2)
Requirement already satisfied: astromodels in /Users/grbphysics/anaconda3/envs/threeML/lib/python3.7/site-packages (from pynchrotron) (2.0.0)
Requirement already satisfied: llvmlite<0.35,>=0.34.0.dev0 in /Users/grbphysics/anaconda3/envs/threeML/lib/python3.7/site-packages (from numba->pynchrotron) (0.34.0)
Requirement already satisfied: setuptools in /Users/grbphysics/anaconda3/envs/threeML/lib/python3.7/site-packages (from numba->pynchrotron) (49.6.0.post20201009)
Requirement already satisfied: scipy>=0.14 in /Users/grbphysics/anaconda3/envs/threeML/lib/python3.7/site-packages (from astromodels->pynchrotron) (1.3.1)
Requirement already satisfied: future in /Users/grbphysics/anaconda3/envs/threeML/lib/python3.7/site-packages (from astromodels->pynchrotron) (0.18.2)
Requirement already satisfied: interpolation in /Users/grbphysics/anaconda3/envs/threeML/lib/python3.7/site-packages (from astromodels->pynchrotron) (2.1.6)
Requirement already satisfied: pandas in /Users/grbphysics/anaconda3/envs/threeML/lib/python3.7/site-packages (from astromodels->pynchrotron) (1.1.3)
Requirement already satisfied: dill in /Users/grbphysics/anaconda3/envs/threeML/lib/python3.7/site-packages (from astromodels->pynchrotron) (0.3.2)
Requirement already satisfied: PyYAML>=5.1 in /Users/grbphysics/anaconda3/envs/threeML/lib/python3.7/site-packages (from astromodels->pynchrotron) (5.3.1)
Requirement already satisfied: astropy>=1.2 in /Users/grbphysics/anaconda3/envs/threeML/lib/python3.7/site-packages (from astromodels->pynchrotron) (3.2.3)
Requirement already satisfied: h5py in /Users/grbphysics/anaconda3/envs/threeML/lib/python3.7/site-packages (from astromodels->pynchrotron) (2.10.0)
ERROR: Could not find a version that satisfies the requirement pytables (from astromodels->pynchrotron) (from versions: none)
ERROR: No matching distribution found for pytables (from astromodels->pynchrotron)
grbphysics@x86_64-apple-darwin13 pynchrotron-master %

**Comment by grburgess** [comment] 2020-10-26 10:12
It seems that the issue is with astromodels itself as this code does not need pytables. You should raise an issue there first. I will investigate it.

**Comment by vikas-chand** [comment] 2020-10-26 10:20
Done.

Thanks.

**Comment by grburgess** [comment] 2020-10-27 08:23
manually installing astromodels should fix the issue until the change is merged into the pypi repo.

**Comment by grburgess** [comment] 2020-10-28 09:43
@asattools The new version of astromodels is out and the installation should be fine. Please let me know if this solves the problem

**Comment by vikas-chand** [comment] 2020-10-28 10:44
Yes, thanks a lot to you and your collaborators.

Regards,
Vikas

**Closed as completed** 2020-10-28 10:47 UTC
